#!/usr/bin/env python3
"""
Check that design system components are used instead of raw HTML.

Reads the component map from config/component-map.json (generated by
design-setup). If config doesn't exist, warns and exits cleanly.

Hook handler: PostToolUse on Edit|Write
Exit 2 with feedback on violations, exit 0 on pass.
"""

import json
import sys
from pathlib import Path


def load_config() -> tuple[dict, dict]:
    """Load component map and paths config."""
    script_dir = Path(__file__).parent.parent

    # Component map
    map_path = script_dir / "config" / "component-map.json"
    component_map = {}
    if map_path.exists():
        try:
            component_map = json.loads(map_path.read_text())
        except json.JSONDecodeError:
            pass

    # Paths config
    paths_path = script_dir / "config" / "paths.json"
    paths_config = {}
    if paths_path.exists():
        try:
            paths_config = json.loads(paths_path.read_text())
        except json.JSONDecodeError:
            pass

    return component_map, paths_config


def is_relevant(file_path: str, paths_config: dict) -> bool:
    """Check if this file should be validated."""
    if not file_path:
        return False

    path = Path(file_path)
    extensions = paths_config.get("ui_file_extensions", [".tsx", ".jsx", ".vue", ".svelte"])

    if path.suffix not in extensions:
        return False

    # Skip test/story files
    if any(p in path.name for p in [".test.", ".spec.", ".stories.", ".story."]):
        return False

    # Skip the design system's own source files
    component_dirs = paths_config.get("component_directories_all", [])
    component_dir = paths_config.get("component_directory", "")
    all_dirs = set(component_dirs)
    if component_dir:
        all_dirs.add(component_dir)

    for d in all_dirs:
        if d and d in str(path):
            return False

    # Skip non-UI directories
    skip_dirs = paths_config.get("skip_directories", [])
    if set(path.parts) & set(skip_dirs):
        return False

    return True


def main():
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)

    file_path = input_data.get("tool_input", {}).get("file_path", "")
    component_map, paths_config = load_config()

    # If no component map exists, setup hasn't been run
    if not component_map:
        # Don't block, just exit. No config = no enforcement.
        sys.exit(0)

    if not is_relevant(file_path, paths_config):
        sys.exit(0)

    path = Path(file_path)
    if not path.exists():
        sys.exit(0)

    try:
        content = path.read_text(errors="ignore")
    except OSError:
        sys.exit(0)

    violations = []

    for line_num, line in enumerate(content.splitlines(), 1):
        stripped = line.strip()

        # Skip comments
        if stripped.startswith("//") or stripped.startswith("{/*") or stripped.startswith("*"):
            continue
        # Skip import statements (importing the design system IS correct)
        if stripped.startswith("import "):
            continue

        for raw_element, replacement in component_map.items():
            # Only match patterns that look like HTML elements (start with "<")
            # This avoids false positives from matching bare words like "button"
            # in variable names, comments, or string content
            if raw_element.startswith("<"):
                if raw_element.lower() in line.lower():
                    violations.append(
                        f"Line {line_num}: found `{raw_element.strip()}` — {replacement}"
                    )

    if not violations:
        sys.exit(0)

    feedback = (
        f"Component violations in {file_path}:\n"
        + "\n".join(f"  - {v}" for v in violations)
        + "\n\nUse design system components instead of raw HTML elements."
    )

    print(feedback, file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
