#!/usr/bin/env python3
"""
Validate that all style values use design tokens, not hardcoded values.

Reads forbidden patterns from config/token-patterns.json (generated by
design-setup). Falls back to sensible defaults if config doesn't exist.

Hook handler: PostToolUse on Edit|Write
Exit 2 with feedback on violations, exit 0 on pass.
"""

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def log_run(script: str, file_path: str, result: str):
    log_dir = Path.cwd() / ".claude" / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    name = Path(file_path).name if file_path else "N/A"
    with open(log_dir / "validation.log", "a") as f:
        f.write(f"{ts} [{script}] {name}: {result}\n")


def load_config() -> dict:
    """Load token patterns config, checking multiple locations."""
    # Check relative to this script (inside the skill)
    script_dir = Path(__file__).parent.parent
    config_path = script_dir / "config" / "token-patterns.json"

    if config_path.exists():
        try:
            return json.loads(config_path.read_text())
        except json.JSONDecodeError:
            pass

    # Fallback: return default patterns
    return {
        "token_system": "unknown",
        "forbidden_patterns": [
            {
                "pattern": r"[\"']#[0-9a-fA-F]{3,8}[\"']",
                "description": "hardcoded hex color",
                "fix_hint": "Use a design token or CSS variable",
            },
            {
                "pattern": r":\s*#[0-9a-fA-F]{3,8}",
                "description": "hardcoded hex color in style",
                "fix_hint": "Use a design token or CSS variable",
            },
            {
                "pattern": r"rgba?\(\s*\d+",
                "description": "hardcoded RGB color",
                "fix_hint": "Use a design token or CSS variable",
            },
        ],
        "allowed_exceptions": [r"0px", r"1px", r"100%"],
    }


def load_paths_config() -> dict:
    """Load paths config to know which files to check."""
    script_dir = Path(__file__).parent.parent
    config_path = script_dir / "config" / "paths.json"

    if config_path.exists():
        try:
            return json.loads(config_path.read_text())
        except json.JSONDecodeError:
            pass

    return {
        "ui_file_extensions": [".tsx", ".jsx", ".vue", ".svelte", ".css", ".scss"],
        "skip_directories": ["node_modules", ".git", "dist", "build"],
        "component_directory": "",
    }


def is_relevant(file_path: str, paths_config: dict) -> bool:
    """Check if this file should be validated."""
    if not file_path:
        return False

    path = Path(file_path)
    extensions = paths_config.get("ui_file_extensions", [".tsx", ".jsx", ".vue", ".svelte", ".css", ".scss"])

    if path.suffix not in extensions:
        return False

    # Skip test/story files
    skip_patterns = [".test.", ".spec.", ".stories.", ".story.", ".d.ts"]
    if any(p in path.name for p in skip_patterns):
        return False

    # Skip directories
    skip_dirs = paths_config.get("skip_directories", [])
    if set(path.parts) & set(skip_dirs):
        return False

    # Skip token source files — they define the tokens, not consume them.
    # Check by matching the end of the path against each token source.
    token_sources = paths_config.get("token_sources", [])
    for ts in token_sources:
        if ts and str(path).endswith(ts):
            return False

    # Skip the component directory's own files (they define the components)
    component_dir = paths_config.get("component_directory", "")
    if component_dir and str(path).replace("\\", "/").find(component_dir) >= 0:
        return False

    return True


def validate_content(content: str, file_path: str, config: dict) -> list[dict]:
    """Check file content against forbidden patterns."""
    violations = []
    forbidden = config.get("forbidden_patterns", [])
    exceptions = config.get("allowed_exceptions", [])

    # Compile exception patterns
    compiled_exceptions = [re.compile(ex) for ex in exceptions]

    for line_num, line in enumerate(content.splitlines(), 1):
        stripped = line.strip()

        # Skip comments
        if stripped.startswith("//") or stripped.startswith("/*") or stripped.startswith("*"):
            continue
        if stripped.startswith("{/*"):
            continue

        for rule in forbidden:
            pattern = rule.get("pattern", "")
            if not pattern:
                continue

            try:
                match = re.search(pattern, line)
            except re.error:
                continue

            if not match:
                continue

            matched_text = match.group()

            # Check exceptions
            is_exception = False
            for exc in compiled_exceptions:
                if exc.search(matched_text):
                    is_exception = True
                    break

            if is_exception:
                continue

            violations.append({
                "line": line_num,
                "match": matched_text,
                "description": rule.get("description", "forbidden pattern"),
                "fix_hint": rule.get("fix_hint", "Use a design token"),
            })

    return violations


def main():
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)

    file_path = input_data.get("tool_input", {}).get("file_path", "")

    config = load_config()
    paths_config = load_paths_config()

    if not is_relevant(file_path, paths_config):
        sys.exit(0)

    # Read the actual file from disk (post-edit, it's already written)
    path = Path(file_path)
    if not path.exists():
        sys.exit(0)

    try:
        content = path.read_text(errors="ignore")
    except OSError:
        sys.exit(0)

    violations = validate_content(content, file_path, config)

    if not violations:
        log_run("validate-tokens", file_path, "PASS")
        print(f"✓ validate-tokens: PASS — no hardcoded values in {Path(file_path).name}")
        sys.exit(0)

    log_run("validate-tokens", file_path, f"FAIL ({len(violations)} violations)")

    # Format feedback
    lines = [f"Design token violations in {file_path}:"]
    for v in violations:
        lines.append(f"  - Line {v['line']}: {v['description']} — found `{v['match']}`. {v['fix_hint']}.")

    token_sources = config.get("token_sources", [])
    if token_sources:
        lines.append(f"\nToken definitions: {', '.join(token_sources)}")

    print("\n".join(lines), file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
